### ISSUE TITLE
Can't make housenumber layer to be visible

### ISSUE THREAD

**Issue by AnSmol** [QwantResearch/erdapfel#328]
Hi.  
I generated vectortiles with housnemuber layer, so it definitely exists, i can see it in raw pbf data:
![image](https://user-images.githubusercontent.com/5318028/62513480-e4e42080-b824-11e9-9594-cb54b60dd7bb.png)

Then I'v added this definition to layers array in basic-style's json:
```json {
            "filter": [
                "==",
                "$type",
                "Point"
            ],
            "id": "housenumber",
            "layout": {
                "text-field": "{housenumber}",
                "text-font": [
                    "Noto Sans Regular"
                ],
                "text-size": 11,
                "visibility": "visible"
            },
            "minzoom": 14,
            "paint": {
                "text-color": "rgba(212, 177, 146, 1)"
            },
            "source": "basemap",
            "source-layer": "housenumber",
            "type": "symbol"
        },
```
But housenumbers just don't appear.
![image](https://user-images.githubusercontent.com/5318028/62514287-6fc61a80-b827-11e9-9514-80584928b969.png)

Should i enable additional layer in some other plaice?
Thanks in advance.

generated style.json from http://erdapfel_instance/style.json:
[style.zip](https://github.com/QwantResearch/erdapfel/files/3470513/style.zip)

**Comment by amatissart** [comment]
Your configuration looks good to me. And no additional step should be necessary to render the new layer.  Maybe some problem with the layers order ? or because of collisions between visible features ?

To debug further you may want to use [mapbox-gl-js API](https://docs.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures). The mapbox Map instance is accessible via `window.map.mb`. For example, to fetch all elements that are rendered from the "housenumber" layer, use:
```js
map.mb.queryRenderedFeatures({layers:['housenumber']})
```

**Comment by AnSmol** [comment]
Thx.
I gave it a shot and got:
`Error: The layer 'housenumber' does not exist in the map's style and cannot be queried for features.`:
![image](https://user-images.githubusercontent.com/5318028/62540590-a2403980-b860-11e9-8a7c-2987ea6c4943.png)

**Comment by amatissart** [comment]
Ok, so it looks like your custom style is not used.  
Can you confirm the "housenumber" layer is present in the response from `/style.json` ?

**Comment by AnSmol** [comment]
it defenetely exists:
![image](https://user-images.githubusercontent.com/5318028/62551631-08cf5280-b875-11e9-9149-1fae93fb772f.png)


I think I have found the root cause of the issue.
Fiddler showed me that real used style was located inside /statics/build/javascript/map.bundle.js file
![image](https://user-images.githubusercontent.com/5318028/62553318-cbb88f80-b877-11e9-9f6a-f52a7abff407.png)
After running  ```npm build``` this file was updated according my style.json and housenumbers eventually appeared.


Sorry if it is something obvious, i don't have much experience with javascript

**Comment by amatissart** [comment]
Ah yes, it makes sense. Once you've updated the style dependency, it's necessary to rebuild the app to update the .js files where the style is bundled.

Whereas the endpoint "/style.json" is defined for external usage, and will generate a new style dynamically. But it's not directly used by the application. Sorry for the confusion.
