### ISSUE TITLE
Searching bar or pub shows cafes

### ISSUE THREAD

**Issue by jakecoppinger** [QwantResearch/erdapfel#475]
I've noticed when clicking the "bar" icon in the map services panel or searching bar or pub, cafes are shown on the map. Is this intended? When I click on a pub POI, it shows the correct icon and says it's a pub, but I can't use the search.

**Comment by remi-dupre** [comment]
Hi!

This is indeed intended as the distinction between bar and cafe can be quite ambiguous (the filter is actually defined [here](https://github.com/QwantResearch/idunn/blob/master/idunn/utils/categories.yml#L58-L64)).

Note that we are working on the integration of a classifier which should help adding more refined categories in the search results, this may be the next improvement to what you appear to be looking for.

**Comment by jonsger** [comment]
It's strange, the [filter](https://github.com/Qwant/idunn/blob/master/idunn/utils/categories.yml#L242) for `bar` includes `bar`,`cafe`,`pub` and `biergarten`. But the last two (pub and biergarten) aren't included in the search...
