### ISSUE TITLE
Text for Favorites and Route is overlapping in German translation

### ISSUE THREAD

**Issue by Spanholz** [QwantResearch/erdapfel#496]
As you can see this part of the text is overlapping in the german translation

![Unbenannt](https://user-images.githubusercontent.com/25983258/71182443-625d7a00-2276-11ea-92dd-d9d8c10b1cd6.PNG)

**Comment by remi-dupre** [comment]
Hi! And sorry for the late reply!

Thanks for your report. These buttons are no longer displayed with recent versions of this panel, so this is no longer an issue.
