### ISSUE TITLE
Swiping on info panel doesn't work correctly on iOS

### ISSUE THREAD

**Issue by map93-osm-2** [QwantResearch/erdapfel#498]
On iOS 12, swiping up or down on the info panel scrolls the whole page, making it difficult to drag. See the attached example:
[qwant_maps_bug.MP4.zip](https://github.com/QwantResearch/erdapfel/files/3990993/qwant_maps_bug.MP4.zip)

**Comment by remi-dupre** [comment]
Hi!

Thanks for the detailed report and sorry for the late reply. I wasn't able to reproduce the issue with Safari, the bug may be fixed on more recent versions of erdapfel.

Don't hesitate to reopen the issue if the problem persists on your side.
