### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by orionseye** [QwantResearch/erdapfel#511]
I am having a hard time installing erdapfel with npm

```
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/QwantResearch/map-style-builder.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
Could you kindly help me out, as seems that some of the packs are outdated?
Tried erlier npm versions with no luck
cheers!

**Comment by orionseye** [comment]
it was an issue with my git path..sorry for inconvinience caused. however, the installation proceedure is very difficult to accomplish, lots of errors, timeout in downloading dependencies etc.
i gave up

**Comment by remi-dupre** [comment]
Hi!

Sorry for the difficulties you encountered, don't hesitate to ask for more help if you get interested in the project again.

If you were running on Windows, note that while the process is way more complicated than on Linux there is now [a bit of documentation](https://github.com/QwantResearch/erdapfel/blob/master/docs/src/windows.md) about how to proceed.

Sorry for the late reply.
